### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by 8bitgentleman** [karlicoss/hypexport#3]
Hi I'm trying to run this and it seems as though the repo is missing some things. There is only a `requirements-dev.txt` though the README calls out a `requirements.txt`. In addition the requirements file is missing `requests` as a dependency.

**Comment by karlicoss** [comment]
Hey, thanks for reporting! Indeed, `requests` should be added to requirements.

I missed it because it was a dependency of Hypothesis API. It's odd that it had passed pylint checks though, perhaps `requests` is a preinstalled package in github CI. 

I added `requirements.txt`, let me know if it works for you now!

**Comment by 8bitgentleman** [comment]
Thanks that did the trick! I've been putting together Dockerfiles that pull the latest code from your export repos, and run them, and save the output in a local file so a missing dependency was screwing with things ;)
